onboarding = false

[keys]
prefix = "ctrl+a"
previous_agent = ["prefix+[", "ctrl+["]
next_agent = ["prefix+]", "ctrl+]"]
switch_workspace = "prefix+shift+1..9"
focus_agent = "prefix+alt+1..9"
last_pane = "prefix+space"
previous_workspace = ["prefix+shift+k", "ctrl+shift+k"]
next_workspace = ["prefix+shift+j", "ctrl+shift+j"]

[[keys.command]]
key = "ctrl+b"
type = "shell"
command = "herdr plugin action invoke herdr-sidebar.open-sidebar"

[keys.indexed]
agents = "alt"

[ui]
show_agent_labels_on_pane_borders = true
agent_panel_sort = "spaces"

[ui.toast]
delivery = "herdr"

[experimental]
pane_history = true
kitty_graphics = true

[theme]
name = "kanagawa"
auto_switch = false

[ui.sound]
enabled = false

[ui.sound.agents]
claude = "off"
codex = "off"
